//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asset()
        {
            this.ConnectAssetManufacturers = new HashSet<ConnectAssetManufacturer>();
            this.users = new HashSet<user>();
        }
    
        public int assetID { get; set; }
        public string assetname { get; set; }
        public string model { get; set; }
        public string category { get; set; }
        public System.DateTime purchasedate { get; set; }
        public Nullable<int> price { get; set; }
        public string serialnumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectAssetManufacturer> ConnectAssetManufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
