//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectAssetManufacturer
    {
        public int connectID { get; set; }
        public int assetFk { get; set; }
        public int manufacturerFk { get; set; }
    
        public virtual asset asset { get; set; }
        public virtual manufacturer manufacturer { get; set; }
    }
}
