//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public manufacturer()
        {
            this.ConnectAssetManufacturers = new HashSet<ConnectAssetManufacturer>();
        }
    
        public int manufacturerID { get; set; }
        public string manufacturerName { get; set; }
        public string manufacturerWebsite { get; set; }
        public string manufacturerEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectAssetManufacturer> ConnectAssetManufacturers { get; set; }
    }
}
