//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userID { get; set; }
        public string username { get; set; }
        public string userpass { get; set; }
        public int assetFk { get; set; }
        public bool adminstatus { get; set; }
    
        public virtual asset asset { get; set; }
    }
}
